services:
  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: redis-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - SPRING_REDIS_HOST=redis
      - SPRING_REDIS_PORT=6379
